import {BaseEntity} from "@core/database/BaseEntity";

export type AutoGeneratedFields = keyof BaseEntity;

export type CreatePayload<T, EntitySpecificOmittedKeys extends keyof T = never> = Omit<T, AutoGeneratedFields | EntitySpecificOmittedKeys>;

export type UpdatePayload<T, EntitySpecificOmittedKeys extends keyof T = never> = Partial<CreatePayload<T, EntitySpecificOmittedKeys>>;

export interface IRepository<Entity extends BaseEntity> {
  findById(id: string | number): Promise<Entity | null>;
  findAll(): Promise<Entity[]>;
  create(data: Partial<Omit<Entity, AutoGeneratedFields>>): Promise<Entity>;
  update(id: string | number, data: Partial<Omit<Entity, AutoGeneratedFields>>): Promise<Entity | null>;
  delete(id: string | number): Promise<boolean>;
  closeConnection(): Promise<void>;
}
