import { Client } from "pg";

import { config } from "src/core/configuration/configuration";
import {AutoGeneratedFields, IRepository } from "@core/database/IRepository";
import {BaseEntity} from "@core/database/BaseEntity";

export type QueryPrepare = {
  columns: string;
  indexes: string;
  values: unknown[];
  lastNumberKey: number;
};

export class SQLRepository<Entity extends BaseEntity> implements IRepository<Entity> {
  private readonly tableName: string;
  private readonly client: Client;

  constructor(tableName: string) {
    this.tableName = tableName;
    this.client = new Client({
      connectionString: config.get("DATABASE_URL"),
    });
    this.client.connect();
    this.client.on("error", (error) => {
      console.log("Something happens: ", error);
      process.exit(1);
    });
  }

  async create(data: Partial<Omit<Entity, AutoGeneratedFields>>): Promise<Entity> {
    const queryTransformed = this.transformQueryData(data);
    const sql = {
      text: `INSERT INTO ${this.tableName}(${queryTransformed.columns}) VALUES(${queryTransformed.indexes}) RETURNING *;`,
      values: queryTransformed.values,
    };
    const result = await this.client.query(sql);
    return result.rows[0];
  }

  async findAll(): Promise<Entity[]> {
    const sql = `SELECT * FROM ${this.tableName};`
    const result = await this.client.query(sql);
    return result.rows as Entity[];
  }

  async findById(id: string | number): Promise<Entity | null> {
    const sql = {
      text: `SELECT * FROM ${this.tableName} WHERE id=$1;`,
      values: [id],
    };
    const result = await this.client.query(sql);
    return result.rows[0];
  }

  async update(id: string | number, data: Partial<Omit<Entity, AutoGeneratedFields>>): Promise<Entity | null> {
    const queryTransformed = this.transformQueryData(data);
    const lastIndex = `$${queryTransformed.lastNumberKey+1}`;
    const sql = {
      text: `UPDATE ${this.tableName} SET ${queryTransformed.columns} = ${queryTransformed.indexes}, updated_at = DEFAULT WHERE id=${lastIndex} RETURNING *;`,
      values: queryTransformed.values.concat(id),
    };
    const result = await this.client.query(sql);
    return result.rows[0];
  }

  async delete(id: string | number): Promise<boolean> {
    const sql = {
      text: `DELETE FROM ${this.tableName} WHERE id=$1 RETURNING *;`,
      values: [id],
    };
    const result = await this.client.query(sql);
    return result.rows[0] || false;
  }

  async closeConnection(): Promise<void> {
    await this.client.end();
  }

  private transformQueryData(data: Partial<Omit<Entity, AutoGeneratedFields>>): QueryPrepare {
    const keys = Object.keys(data);
    const values = Object.values(data);
    const sequence = Array.from({ length: keys.length }, (_, i) => 1 + i);
    const sequenceMapped = sequence.map(digit => `$${digit}`);
    return {
      columns: keys.join(","),
      values,
      indexes: sequenceMapped.join(","),
      lastNumberKey: keys.length,
    };
  }
}
